---
name: Snapmaker Monitor
version: dev
slug: snapmaker
description: Python script to monitor Snapmaker 2.0 printer status and send updates to Home Assistant.
url: https://github.com/nemesisre/SnapMaker2.0_Home-Assistant
codenotary: nemesissre@gmail.com
arch:
  - aarch64
  - amd64
homeassistant_api: true
options:
  ha_token: null
  ha_webhook_url: null
  sm_ip: null
  sm_port: 8080
  sm_token: null
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ha_token: "str"
  ha_webhook_url: "str"
  sm_ip: "str"
  sm_port: "str"
  sm_token: "str"
environment:
  HA_TOKEN: ha_token
  HA_WEBHOOK_URL: ha_webhook_url
  SM_IP: sm_ip
  SM_PORT: sm_port
  SM_TOKEN: sm_token
