---
name: Snapmaker Monitor
version: dev
slug: snapmaker-monitor
description: Python script to monitor Snapmaker 2.0 printer status and send updates to Home Assistant.
url: https://github.com/nemesisre/SnapMaker2.0_Home-Assistant
codenotary: nemesissre@gmail.com
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  option_ha_token: null
  option_ha_webhook_url: null
  option_sm_ip: null
  option_sm_port: 8080
  option_sm_token: "generate_token"
  option_log_level: info
schema:
  option_log_level: list(trace|debug|info|notice|warning|error|fatal)?
  option_ha_token: str
  option_ha_webhook_url: str
  option_sm_ip: str
  option_sm_port: int(1,65535)?
  option_sm_token: str
